import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppTheme from '@/app/lib/theme/AppTheme';
import CssBaseline from '@mui/material/CssBaseline';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitColorSchemeScript attribute='data-mui-color-scheme' />
        <AppRouterCacheProvider>
          <AppTheme>
            <CssBaseline enableColorScheme>
            {children}

            </CssBaseline>

          </AppTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
